run 65ns
puts "=== 65ns (ADDI x1 near WB) ==="
puts "alu_result_wb=[get_value /tb_top/uut/alu_result_wb]"
puts "alu_result_mem=[get_value /tb_top/uut/alu_result_mem]"
puts "alu_result_ex=[get_value /tb_top/uut/alu_result_ex]"
puts "alu_in_a=[get_value /tb_top/uut/alu_in_a]"
puts "alu_in_b=[get_value /tb_top/uut/alu_in_b]"
puts "alu_ctrl=[get_value /tb_top/uut/alu_ctrl]"
puts "reg_write_wb=[get_value /tb_top/uut/reg_write_wb]"
puts "rd_addr_wb=[get_value /tb_top/uut/rd_addr_wb]"
puts "pc_if=[get_value /tb_top/uut/pc_if]"
puts "instr_id=[get_value /tb_top/uut/instr_id]"
puts "stall_bram=[get_value /tb_top/uut/stall_bram]"
run 10ns
puts "=== 75ns ==="
puts "alu_result_wb=[get_value /tb_top/uut/alu_result_wb]"
puts "alu_result_mem=[get_value /tb_top/uut/alu_result_mem]"
puts "alu_result_ex=[get_value /tb_top/uut/alu_result_ex]"
puts "alu_in_a=[get_value /tb_top/uut/alu_in_a]"
puts "alu_in_b=[get_value /tb_top/uut/alu_in_b]"
puts "alu_ctrl=[get_value /tb_top/uut/alu_ctrl]"
puts "reg_write_wb=[get_value /tb_top/uut/reg_write_wb]"
puts "rd_addr_wb=[get_value /tb_top/uut/rd_addr_wb]"
puts "stall_bram=[get_value /tb_top/uut/stall_bram]"
exit
