run 45ns
puts "=== 45ns (1 cycle after rst=0) ==="
puts "stall_bram=[get_value /tb_top/uut/stall_bram]"
puts "stall_loaduse=[get_value /tb_top/uut/stall_loaduse]"
puts "stall=[get_value /tb_top/uut/stall]"
puts "flush_id_ex=[get_value /tb_top/uut/flush_id_ex]"
puts "pc_sel=[get_value /tb_top/uut/pc_sel]"
puts "instr_if=[get_value /tb_top/uut/instr_if]"
puts "instr_id=[get_value /tb_top/uut/instr_id]"
puts "imm_id=[get_value /tb_top/uut/imm_id]"
puts "alu_src_id=[get_value /tb_top/uut/alu_src_id]"
puts "reg_write_id=[get_value /tb_top/uut/reg_write_id]"
run 10ns
puts "=== 55ns (cycle 2 after rst) ==="
puts "stall_bram=[get_value /tb_top/uut/stall_bram]"
puts "flush_id_ex=[get_value /tb_top/uut/flush_id_ex]"
puts "imm_ex=[get_value /tb_top/uut/imm_ex]"
puts "alu_src_ex=[get_value /tb_top/uut/alu_src_ex]"
puts "alu_in_a=[get_value /tb_top/uut/alu_in_a]"
puts "alu_in_b=[get_value /tb_top/uut/alu_in_b]"
puts "alu_result_ex=[get_value /tb_top/uut/alu_result_ex]"
puts "reg_write_ex=[get_value /tb_top/uut/reg_write_ex]"
puts "rd_addr_ex=[get_value /tb_top/uut/rd_addr_ex]"
exit
